# TensorFlow LSTM (Many-to-One) with Daily Bitcoin Return Target

This notebook builds a **many-to-one LSTM** that predicts the **next daily Bitcoin log return**:

```text
r_t = log(P_t / P_{t-1})
```

where `P_t` is the daily close price.

Features are constructed from the 5-minute source data and aggregated to daily frequency:
- `daily_log_return`
- `daily_volatility` (intraday 5-minute return standard deviation per day)
- `volatility_7d` (7-day rolling average of `daily_volatility`)

It uses:
- chronological **train / validation / test** split
- **walk-forward validation** with a rolling **30-day training window**
- ~50 hyperparameter combinations in grid search
- checkpointing so the best model is always saved, even if training is interrupted.

In [1]:
from __future__ import annotations

import atexit
import importlib.util
import json
import random
import shutil
import socket
import subprocess
import sys
import time
from itertools import product
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.preprocessing import StandardScaler

print('TensorFlow:', tf.__version__)

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1780249381.197655 1648939 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1780249381.336587 1648939 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1780249395.130193 1648939 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

TensorFlow: 2.21.0

In [2]:
# Paths and core configuration
DATA_PATH = Path('data/BTC/BTC_USD_coinbase_spot_5min.csv')
ARTIFACTS_DIR = Path('artifacts/lstm_walk_forward')
ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)

TIMESTAMP_COL = 'timestamp_utc'
TARGET_COL = 'target_next_daily_log_return'
FEATURE_COLS = ['daily_log_return', 'daily_volatility', 'volatility_7d']

TRAIN_WINDOW_DAYS = 30
VAL_PERIOD_DAYS = 30
TEST_PERIOD_DAYS = 30
FOLD_STEP_DAYS = 3
FOLD_HORIZON_DAYS = 3

MAX_EPOCHS = 25
PATIENCE = 4
GRID_LIMIT = 50
SEED = 42

USE_CUDA_IF_AVAILABLE = True
REQUIRE_CUDA = True
ENABLE_XLA = True
ENABLE_MIXED_PRECISION = True

AUTO_START_TENSORBOARD = True
TENSORBOARD_HOST = '127.0.0.1'
TENSORBOARD_PORT = 6006
TENSORBOARD_ROOT_LOGDIR = ARTIFACTS_DIR / 'tensorboard'
TENSORBOARD_ROOT_LOGDIR.mkdir(parents=True, exist_ok=True)
TENSORBOARD_PROCESS: subprocess.Popen | None = None
HAS_TENSORBOARD = importlib.util.find_spec('tensorboard') is not None
TENSORBOARD_WARNING_EMITTED = False

if not HAS_TENSORBOARD:
    AUTO_START_TENSORBOARD = False
    print('TensorBoard package is missing. Install with: uv pip install tensorboard')


def set_seed(seed: int = SEED) -> None:
    random.seed(seed)
    np.random.seed(seed)
    tf.keras.utils.set_random_seed(seed)


def configure_runtime_for_speed(
    use_cuda_if_available: bool = USE_CUDA_IF_AVAILABLE,
    require_cuda: bool = REQUIRE_CUDA,
    enable_xla: bool = ENABLE_XLA,
    enable_mixed_precision: bool = ENABLE_MIXED_PRECISION,
) -> list[tf.config.PhysicalDevice]:
    if enable_xla:
        tf.config.optimizer.set_jit(True)

    gpus = tf.config.list_physical_devices('GPU')

    if use_cuda_if_available and gpus:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)

        if enable_mixed_precision:
            tf.keras.mixed_precision.set_global_policy('mixed_float16')
    else:
        tf.keras.mixed_precision.set_global_policy('float32')

    if require_cuda and not gpus:
        raise RuntimeError(
            'CUDA GPU was required but not detected. '
            'Launch from WSL with: bash scripts/wsl_jupyter.sh and use kernel Python (LSTM WSL GPU)'
        )

    print('Detected GPUs:', gpus)
    print('XLA enabled:', enable_xla)
    print('Mixed precision policy:', tf.keras.mixed_precision.global_policy())
    return gpus


set_seed(SEED)
GPUS = configure_runtime_for_speed()

Detected GPUs: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
XLA enabled: True
Mixed precision policy: <DTypePolicy "mixed_float16">

In [3]:
# Load 5-minute data and build daily target/features
raw = pd.read_csv(DATA_PATH)
raw[TIMESTAMP_COL] = pd.to_datetime(raw[TIMESTAMP_COL], utc=True)
raw = raw.sort_values(TIMESTAMP_COL).reset_index(drop=True)

raw['log_close_5m'] = np.log(raw['close'])
raw['log_return_5m'] = raw['log_close_5m'].diff()

daily = raw.set_index(TIMESTAMP_COL).resample('1D').agg(close=('close', 'last'))
daily_intraday_vol = raw.set_index(TIMESTAMP_COL)['log_return_5m'].resample('1D').std().rename('daily_volatility')

daily = daily.join(daily_intraday_vol)
daily['daily_log_return'] = np.log(daily['close'] / daily['close'].shift(1))
daily['volatility_7d'] = daily['daily_volatility'].rolling(7).mean()
daily[TARGET_COL] = daily['daily_log_return'].shift(-1)

df = daily.reset_index()[[TIMESTAMP_COL, *FEATURE_COLS, TARGET_COL]].dropna().reset_index(drop=True)

max_time = df[TIMESTAMP_COL].max()
test_start = max_time - pd.Timedelta(days=TEST_PERIOD_DAYS)
val_start = test_start - pd.Timedelta(days=VAL_PERIOD_DAYS)

split_masks = {
    'train': df[TIMESTAMP_COL] < val_start,
    'validation': (df[TIMESTAMP_COL] >= val_start) & (df[TIMESTAMP_COL] < test_start),
    'test': df[TIMESTAMP_COL] >= test_start,
}

split_summary = pd.DataFrame(
    {
        name: {
            'rows': int(mask.sum()),
            'start': df.loc[mask, TIMESTAMP_COL].min(),
            'end': df.loc[mask, TIMESTAMP_COL].max(),
        }
        for name, mask in split_masks.items()
    }
).T

print('Prepared daily rows:', len(df))
print('Target:', 'r_t = log(P_t / P_{t-1}), predicted one day ahead via shift(-1)')
print('Validation starts:', val_start)
print('Test starts:', test_start)
display(split_summary)

Prepared daily rows: 3646
Target: r_t = log(P_t / P_{t-1}), predicted one day ahead via shift(-1)
Validation starts: 2026-02-11 00:00:00+00:00
Test starts: 2026-03-13 00:00:00+00:00

            rows                      start                        end
train       3585  2016-04-19 00:00:00+00:00  2026-02-10 00:00:00+00:00
validation    30  2026-02-11 00:00:00+00:00  2026-03-12 00:00:00+00:00
test          31  2026-03-13 00:00:00+00:00  2026-04-12 00:00:00+00:00

In [4]:
def make_sequences(features: np.ndarray, targets: np.ndarray, seq_len: int) -> tuple[np.ndarray, np.ndarray]:
    x_list: list[np.ndarray] = []
    y_list: list[float] = []

    for idx in range(seq_len, len(features)):
        x_list.append(features[idx - seq_len:idx])
        y_list.append(targets[idx])

    if not x_list:
        return (
            np.empty((0, seq_len, features.shape[1]), dtype=np.float32),
            np.empty((0,), dtype=np.float32),
        )

    return np.asarray(x_list, dtype=np.float32), np.asarray(y_list, dtype=np.float32)


def build_walk_forward_folds(
    data: pd.DataFrame,
    start_time: pd.Timestamp,
    end_time: pd.Timestamp,
    train_window_days: int,
    step_days: int,
    horizon_days: int,
) -> list[dict]:
    folds: list[dict] = []
    fold_id = 0
    cursor = start_time

    while cursor < end_time:
        eval_start = cursor
        eval_end = min(eval_start + pd.Timedelta(days=horizon_days), end_time)
        train_end = eval_start
        train_start = train_end - pd.Timedelta(days=train_window_days)

        train_rows = data[(data[TIMESTAMP_COL] >= train_start) & (data[TIMESTAMP_COL] < train_end)]
        eval_rows = data[(data[TIMESTAMP_COL] >= eval_start) & (data[TIMESTAMP_COL] < eval_end)]

        if len(train_rows) > 0 and len(eval_rows) > 0:
            folds.append(
                {
                    'fold_id': fold_id,
                    'train_start': train_start,
                    'train_end': train_end,
                    'eval_start': eval_start,
                    'eval_end': eval_end,
                }
            )
            fold_id += 1

        cursor = cursor + pd.Timedelta(days=step_days)

    return folds


def describe_folds(name: str, folds: list[dict]) -> None:
    fold_df = pd.DataFrame(folds)
    print(f'{name} folds: {len(folds)}')
    if not fold_df.empty:
        display(fold_df.head())


val_folds = build_walk_forward_folds(
    data=df,
    start_time=val_start,
    end_time=test_start,
    train_window_days=TRAIN_WINDOW_DAYS,
    step_days=FOLD_STEP_DAYS,
    horizon_days=FOLD_HORIZON_DAYS,
)

test_folds = build_walk_forward_folds(
    data=df,
    start_time=test_start,
    end_time=max_time,
    train_window_days=TRAIN_WINDOW_DAYS,
    step_days=FOLD_STEP_DAYS,
    horizon_days=FOLD_HORIZON_DAYS,
)

describe_folds('Validation', val_folds)
describe_folds('Test', test_folds)

Validation folds: 10

,fold_id,train_start,train_end,eval_start,eval_end
0,0,2026-01-12 00:00:00+00:00,2026-02-11 00:00:00+00:00,2026-02-11 00:00:00+00:00,2026-02-14 00:00:00+00:00
1,1,2026-01-15 00:00:00+00:00,2026-02-14 00:00:00+00:00,2026-02-14 00:00:00+00:00,2026-02-17 00:00:00+00:00
2,2,2026-01-18 00:00:00+00:00,2026-02-17 00:00:00+00:00,2026-02-17 00:00:00+00:00,2026-02-20 00:00:00+00:00
3,3,2026-01-21 00:00:00+00:00,2026-02-20 00:00:00+00:00,2026-02-20 00:00:00+00:00,2026-02-23 00:00:00+00:00
4,4,2026-01-24 00:00:00+00:00,2026-02-23 00:00:00+00:00,2026-02-23 00:00:00+00:00,2026-02-26 00:00:00+00:00

Test folds: 10

,fold_id,train_start,train_end,eval_start,eval_end
0,0,2026-02-11 00:00:00+00:00,2026-03-13 00:00:00+00:00,2026-03-13 00:00:00+00:00,2026-03-16 00:00:00+00:00
1,1,2026-02-14 00:00:00+00:00,2026-03-16 00:00:00+00:00,2026-03-16 00:00:00+00:00,2026-03-19 00:00:00+00:00
2,2,2026-02-17 00:00:00+00:00,2026-03-19 00:00:00+00:00,2026-03-19 00:00:00+00:00,2026-03-22 00:00:00+00:00
3,3,2026-02-20 00:00:00+00:00,2026-03-22 00:00:00+00:00,2026-03-22 00:00:00+00:00,2026-03-25 00:00:00+00:00
4,4,2026-02-23 00:00:00+00:00,2026-03-25 00:00:00+00:00,2026-03-25 00:00:00+00:00,2026-03-28 00:00:00+00:00

In [5]:
def build_model(seq_len: int, n_features: int, lstm_units: int, dropout: float, learning_rate: float) -> tf.keras.Model:
    layers: list[tf.keras.layers.Layer] = [
        tf.keras.layers.Input(shape=(seq_len, n_features)),
        # Keep recurrent_dropout=0 for fast cuDNN GPU kernels when CUDA is available.
        tf.keras.layers.LSTM(lstm_units, recurrent_dropout=0.0),
    ]

    if dropout > 0.0:
        layers.append(tf.keras.layers.Dropout(dropout))

    layers.extend([
        tf.keras.layers.Dense(16, activation='relu'),
        tf.keras.layers.Dense(1, dtype='float32'),
    ])

    model = tf.keras.Sequential(layers)
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
        loss='mse',
        metrics=[tf.keras.metrics.MeanAbsoluteError(name='mae')],
    )
    return model


def prepare_fold_data(data: pd.DataFrame, fold: dict, seq_len: int) -> dict | None:
    train_df = data[(data[TIMESTAMP_COL] >= fold['train_start']) & (data[TIMESTAMP_COL] < fold['train_end'])].copy()
    eval_df = data[(data[TIMESTAMP_COL] >= fold['eval_start']) & (data[TIMESTAMP_COL] < fold['eval_end'])].copy()

    if len(train_df) <= seq_len + 10 or len(eval_df) == 0:
        return None

    scaler = StandardScaler()
    train_features = scaler.fit_transform(train_df[FEATURE_COLS])
    eval_features = scaler.transform(eval_df[FEATURE_COLS])

    train_targets = train_df[TARGET_COL].to_numpy(dtype=np.float32)
    eval_targets = eval_df[TARGET_COL].to_numpy(dtype=np.float32)

    x_all, y_all = make_sequences(train_features, train_targets, seq_len)
    if len(x_all) < 12:
        return None

    split_idx = int(len(x_all) * 0.8)
    if split_idx <= 0 or split_idx >= len(x_all):
        return None

    x_train = x_all[:split_idx]
    y_train = y_all[:split_idx]
    x_val = x_all[split_idx:]
    y_val = y_all[split_idx:]

    combined_features = np.vstack([train_features, eval_features])
    combined_targets = np.concatenate([train_targets, eval_targets])

    x_eval_list: list[np.ndarray] = []
    y_eval_list: list[float] = []

    eval_start_idx = len(train_df)
    for idx in range(eval_start_idx, len(combined_features)):
        start = idx - seq_len
        if start < 0:
            continue
        x_eval_list.append(combined_features[start:idx])
        y_eval_list.append(float(combined_targets[idx]))

    if not x_eval_list:
        return None

    x_eval = np.asarray(x_eval_list, dtype=np.float32)
    y_eval = np.asarray(y_eval_list, dtype=np.float32)

    return {
        'x_train': x_train,
        'y_train': y_train,
        'x_val': x_val,
        'y_val': y_val,
        'x_eval': x_eval,
        'y_eval': y_eval,
        'eval_timestamps': eval_df[TIMESTAMP_COL].to_numpy(),
    }


def is_port_open(host: str, port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.settimeout(0.2)
        return sock.connect_ex((host, port)) == 0


def ensure_tensorboard_running(log_dir: Path) -> str | None:
    global TENSORBOARD_PROCESS

    if not HAS_TENSORBOARD:
        return None

    if not AUTO_START_TENSORBOARD:
        return None

    log_dir.mkdir(parents=True, exist_ok=True)
    url = f'http://{TENSORBOARD_HOST}:{TENSORBOARD_PORT}'

    if is_port_open(TENSORBOARD_HOST, TENSORBOARD_PORT):
        return url

    # Restart stale process handle if it exists.
    if TENSORBOARD_PROCESS is not None and TENSORBOARD_PROCESS.poll() is not None:
        TENSORBOARD_PROCESS = None

    if TENSORBOARD_PROCESS is None:
        cmd = [
            sys.executable,
            '-m',
            'tensorboard.main',
            '--logdir',
            str(log_dir),
            '--host',
            TENSORBOARD_HOST,
            '--port',
            str(TENSORBOARD_PORT),
            '--reload_interval',
            '5',
        ]
        TENSORBOARD_PROCESS = subprocess.Popen(
            cmd,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )

    for _ in range(20):
        if is_port_open(TENSORBOARD_HOST, TENSORBOARD_PORT):
            print(f'TensorBoard started: {url} (logdir={log_dir})')
            return url
        time.sleep(0.25)

    print(f'TensorBoard process launched but port {TENSORBOARD_PORT} is not ready yet.')
    return url


def stop_tensorboard() -> None:
    global TENSORBOARD_PROCESS
    if TENSORBOARD_PROCESS is None:
        return

    if TENSORBOARD_PROCESS.poll() is None:
        TENSORBOARD_PROCESS.terminate()
    TENSORBOARD_PROCESS = None


atexit.register(stop_tensorboard)


def regression_metrics(y_true: np.ndarray, y_pred: np.ndarray) -> dict:
    rmse = float(np.sqrt(mean_squared_error(y_true, y_pred)))
    mae = float(mean_absolute_error(y_true, y_pred))
    return {'rmse': rmse, 'mae': mae}


def train_one_fold(
    data: pd.DataFrame,
    fold: dict,
    params: dict,
    combo_dir: Path,
    fold_set_name: str,
) -> dict | None:
    fold_data = prepare_fold_data(data, fold, seq_len=params['seq_len'])
    if fold_data is None:
        return None

    fold_dir = combo_dir / fold_set_name / f"fold_{fold['fold_id']:03d}"
    fold_dir.mkdir(parents=True, exist_ok=True)

    checkpoint_path = fold_dir / 'best_model.keras'
    backup_dir = fold_dir / 'backup'
    tensorboard_log_dir = TENSORBOARD_ROOT_LOGDIR / fold_set_name / combo_dir.name / f"fold_{fold['fold_id']:03d}"
    tensorboard_url = ensure_tensorboard_running(TENSORBOARD_ROOT_LOGDIR)

    model = build_model(
        seq_len=params['seq_len'],
        n_features=len(FEATURE_COLS),
        lstm_units=params['lstm_units'],
        dropout=params['dropout'],
        learning_rate=params['learning_rate'],
    )

    callbacks = [
        tf.keras.callbacks.ModelCheckpoint(
            filepath=str(checkpoint_path),
            monitor='val_loss',
            save_best_only=True,
            verbose=0,
        ),
        tf.keras.callbacks.BackupAndRestore(
            backup_dir=str(backup_dir),
            delete_checkpoint=False,
        ),
        tf.keras.callbacks.EarlyStopping(
            monitor='val_loss',
            patience=PATIENCE,
            restore_best_weights=True,
        ),
    ]

    global TENSORBOARD_WARNING_EMITTED
    if HAS_TENSORBOARD:
        callbacks.insert(
            2,
            tf.keras.callbacks.TensorBoard(
                log_dir=str(tensorboard_log_dir),
                histogram_freq=0,
                write_graph=True,
                update_freq='epoch',
                profile_batch=0,
            ),
        )
    elif not TENSORBOARD_WARNING_EMITTED:
        print('TensorBoard callback disabled because the tensorboard package is not installed.')
        TENSORBOARD_WARNING_EMITTED = True

    history = model.fit(
        fold_data['x_train'],
        fold_data['y_train'],
        validation_data=(fold_data['x_val'], fold_data['y_val']),
        epochs=MAX_EPOCHS,
        batch_size=params['batch_size'],
        shuffle=False,
        verbose=0,
        callbacks=callbacks,
    )

    best_model = tf.keras.models.load_model(checkpoint_path) if checkpoint_path.exists() else model
    y_pred = best_model.predict(fold_data['x_eval'], verbose=0).reshape(-1)

    metrics = regression_metrics(fold_data['y_eval'], y_pred)

    pred_df = pd.DataFrame(
        {
            TIMESTAMP_COL: fold_data['eval_timestamps'],
            'y_true': fold_data['y_eval'],
            'y_pred': y_pred,
        }
    )
    pred_path = fold_dir / 'predictions.csv'
    pred_df.to_csv(pred_path, index=False)

    return {
        'fold_id': fold['fold_id'],
        'rmse': metrics['rmse'],
        'mae': metrics['mae'],
        'model_path': str(checkpoint_path),
        'predictions_path': str(pred_path),
        'epochs_ran': len(history.history.get('loss', [])),
        'tensorboard_log_dir': str(tensorboard_log_dir),
        'tensorboard_url': tensorboard_url,
    }


def build_grid(limit: int = GRID_LIMIT, seed: int = SEED) -> list[dict]:
    base_grid = {
        'seq_len': [3, 5, 7, 10, 14],
        'lstm_units': [16, 32],
        'dropout': [0.0, 0.2],
        'learning_rate': [1e-3, 5e-4, 2e-4],
        'batch_size': [8, 16],
    }

    all_combinations = [
        {
            'seq_len': seq_len,
            'lstm_units': lstm_units,
            'dropout': dropout,
            'learning_rate': learning_rate,
            'batch_size': batch_size,
        }
        for seq_len, lstm_units, dropout, learning_rate, batch_size in product(
            base_grid['seq_len'],
            base_grid['lstm_units'],
            base_grid['dropout'],
            base_grid['learning_rate'],
            base_grid['batch_size'],
        )
    ]

    rng = random.Random(seed)
    rng.shuffle(all_combinations)
    return all_combinations[:limit]


def run_grid_search(
    data: pd.DataFrame,
    folds: list[dict],
    grid: list[dict],
    output_dir: Path,
) -> tuple[pd.DataFrame, dict, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)

    results: list[dict] = []
    best_score = float('inf')
    best_params: dict | None = None
    best_model_path = output_dir / 'best_model_overall.keras'

    for idx, params in enumerate(grid, start=1):
        combo_name = f'combo_{idx:03d}'
        combo_dir = output_dir / combo_name
        combo_dir.mkdir(parents=True, exist_ok=True)

        fold_records: list[dict] = []
        for fold in folds:
            fold_result = train_one_fold(
                data=data,
                fold=fold,
                params=params,
                combo_dir=combo_dir,
                fold_set_name='validation',
            )
            if fold_result is not None:
                fold_records.append(fold_result)

        if not fold_records:
            combo_rmse = float('inf')
            combo_mae = float('inf')
            best_fold_model = None
        else:
            combo_rmse = float(np.mean([r['rmse'] for r in fold_records]))
            combo_mae = float(np.mean([r['mae'] for r in fold_records]))
            best_fold_model = min(fold_records, key=lambda x: x['rmse'])['model_path']

        row = {
            'combo_id': combo_name,
            'val_rmse_mean': combo_rmse,
            'val_mae_mean': combo_mae,
            'n_folds_trained': len(fold_records),
            **params,
            'best_fold_model': best_fold_model,
        }
        results.append(row)

        pd.DataFrame(results).sort_values('val_rmse_mean').to_csv(
            output_dir / 'grid_search_results_live.csv',
            index=False,
        )

        if combo_rmse < best_score and best_fold_model is not None:
            best_score = combo_rmse
            best_params = params.copy()
            shutil.copy2(best_fold_model, best_model_path)
            with (output_dir / 'best_model_metadata.json').open('w', encoding='utf-8') as f:
                json.dump(
                    {
                        'best_combo': combo_name,
                        'best_val_rmse_mean': best_score,
                        'best_params': best_params,
                        'source_model': best_fold_model,
                    },
                    f,
                    indent=2,
                )

        print(f"[{idx:03d}/{len(grid):03d}] {combo_name} | mean_val_rmse={combo_rmse:.8f} | folds={len(fold_records)}")

    results_df = pd.DataFrame(results).sort_values('val_rmse_mean').reset_index(drop=True)
    results_df.to_csv(output_dir / 'grid_search_results_final.csv', index=False)

    if best_params is None:
        raise RuntimeError('No model could be trained. Try smaller seq_len or fewer folds.')

    return results_df, best_params, best_model_path

In [ ]:
# Run grid search (~50 combinations) on validation folds
val_grid = build_grid(limit=GRID_LIMIT, seed=SEED)
print('Grid combinations:', len(val_grid))

grid_dir = ARTIFACTS_DIR / 'grid_search'
results_df, best_params, best_model_path = run_grid_search(
    data=df,
    folds=val_folds,
    grid=val_grid,
    output_dir=grid_dir,
)

print('Best params:', best_params)
print('Best model saved at:', best_model_path)
display(results_df.head(10))

Grid combinations: 50

I0000 00:00:1780249411.273762 1648939 gpu_device.cc:2043] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 21456 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4090, pci bus id: 0000:01:00.0, compute capability: 8.9
E0000 00:00:1780249412.671534 1648939 util.cc:131] oneDNN supports DT_HALF only on platforms with AVX-512. Falling back to the default Eigen-based implementation if present.
I0000 00:00:1780249412.676269 3091986 service.cc:153] XLA service 0x77b7240f9ca0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1780249412.676288 3091986 service.cc:161]   StreamExecutor [0]: NVIDIA GeForce RTX 4090, Compute Capability 8.9 (Driver: 13.2.0; Runtime: 12.9.0; Toolkit: 12.5.0; DNN: 9.23.0)
I0000 00:00:1780249412.696162 3091986 cuda_dnn.cc:461] Loaded cuDNN version 92300
I0000 00:00:1780249412.934938 3091986 device_compiler.h:208] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
I0000 00:00:1780249413.390922 3091986 dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.

WARNING:tensorflow:5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x77b8ecbe96c0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 6 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x77b8ecb3f100> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
[001/050] combo_001 | mean_val_rmse=0.02688996 | folds=10

I0000 00:00:1780249424.469191 3091987 dot_merger.cc:481] Merging Dots in computation: cluster_38__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_0__XlaNumResourceArgs_7_.5

[002/050] combo_002 | mean_val_rmse=0.02558153 | folds=10
[003/050] combo_003 | mean_val_rmse=0.02648406 | folds=10

I0000 00:00:1780249445.243836 3091988 dot_merger.cc:481] Merging Dots in computation: cluster_92__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6
I0000 00:00:1780249448.245774 3091977 dot_merger.cc:481] Merging Dots in computation: cluster_92__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6

[004/050] combo_004 | mean_val_rmse=0.02392807 | folds=10

I0000 00:00:1780249451.713621 3091978 dot_merger.cc:481] Merging Dots in computation: cluster_108__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_0__XlaNumResourceArgs_8_.5
I0000 00:00:1780249458.476877 3091978 dot_merger.cc:481] Merging Dots in computation: cluster_126__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_0__XlaNumResourceArgs_8_.5
I0000 00:00:1780249462.211841 3091985 dot_merger.cc:481] Merging Dots in computation: cluster_140__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_0__XlaNumResourceArgs_8_.5

[005/050] combo_005 | mean_val_rmse=0.02296550 | folds=10

I0000 00:00:1780249468.776152 3091979 dot_merger.cc:481] Merging Dots in computation: cluster_167__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6
I0000 00:00:1780249471.582965 3091979 dot_merger.cc:481] Merging Dots in computation: cluster_167__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6
I0000 00:00:1780249480.733425 3091982 dot_merger.cc:481] Merging Dots in computation: cluster_194__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6
I0000 00:00:1780249482.417740 3091974 dot_merger.cc:481] Merging Dots in computation: cluster_194__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6

[006/050] combo_006 | mean_val_rmse=0.02560913 | folds=10

I0000 00:00:1780249484.682721 3091984 dot_merger.cc:481] Merging Dots in computation: cluster_208__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_0__XlaNumResourceArgs_8_.5
I0000 00:00:1780249488.765914 3091979 dot_merger.cc:481] Merging Dots in computation: cluster_222__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_0__XlaNumResourceArgs_8_.5
I0000 00:00:1780249491.621291 3091980 dot_merger.cc:481] Merging Dots in computation: cluster_236__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_0__XlaNumResourceArgs_8_.5

WARNING:tensorflow:5 out of the last 19 calls to <function TensorFlowTrainer._make_function.<locals>.multi_step_on_iterator at 0x77b85f9072e0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

I0000 00:00:1780249496.878978 3091980 dot_merger.cc:481] Merging Dots in computation: cluster_258__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_0__XlaNumResourceArgs_8_.5

WARNING:tensorflow:5 out of the last 17 calls to <function TensorFlowTrainer._make_function.<locals>.multi_step_on_iterator at 0x77b8603c7240> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

I0000 00:00:1780249500.879676 3091984 dot_merger.cc:481] Merging Dots in computation: cluster_272__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_0__XlaNumResourceArgs_8_.5

[007/050] combo_007 | mean_val_rmse=0.02681166 | folds=10

I0000 00:00:1780249506.040029 3091984 dot_merger.cc:481] Merging Dots in computation: cluster_287__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_0__XlaNumResourceArgs_7_.5
I0000 00:00:1780249512.381093 3091973 dot_merger.cc:481] Merging Dots in computation: cluster_301__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_0__XlaNumResourceArgs_7_.5
I0000 00:00:1780249515.221507 3091973 dot_merger.cc:481] Merging Dots in computation: cluster_315__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_0__XlaNumResourceArgs_7_.5
I0000 00:00:1780249517.888512 3091973 dot_merger.cc:481] Merging Dots in computation: cluster_329__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_0__XlaNumResourceArgs_7_.5
I0000 00:00:1780249521.349675 3091980 dot_merger.cc:481] Merging Dots in computation: cluster_343__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_0__XlaNumResourceArgs_7_.5
I0000 00:00:1780249524.937424 3091986 dot_merger.cc:481] Merging Dots in computation: cluster_357__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_0__XlaNumResourceArgs_7_.5
I0000 00:00:1780249527.543327 3091984 dot_merger.cc:481] Merging Dots in computation: cluster_371__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_0__XlaNumResourceArgs_7_.5
I0000 00:00:1780249530.473981 3091973 dot_merger.cc:481] Merging Dots in computation: cluster_385__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_0__XlaNumResourceArgs_7_.5
I0000 00:00:1780249532.809764 3091973 dot_merger.cc:481] Merging Dots in computation: cluster_399__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_0__XlaNumResourceArgs_7_.5
I0000 00:00:1780249535.516886 3091988 dot_merger.cc:481] Merging Dots in computation: cluster_413__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_0__XlaNumResourceArgs_7_.5

[008/050] combo_008 | mean_val_rmse=0.03083258 | folds=10

I0000 00:00:1780249538.841329 3091988 dot_merger.cc:481] Merging Dots in computation: cluster_428__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249540.735183 3091988 dot_merger.cc:481] Merging Dots in computation: cluster_428__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249542.400852 3091974 dot_merger.cc:481] Merging Dots in computation: cluster_443__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249547.755947 3091979 dot_merger.cc:481] Merging Dots in computation: cluster_443__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249551.151484 3091984 dot_merger.cc:481] Merging Dots in computation: cluster_458__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249552.806322 3091979 dot_merger.cc:481] Merging Dots in computation: cluster_458__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249554.640685 3091988 dot_merger.cc:481] Merging Dots in computation: cluster_473__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249556.355232 3091974 dot_merger.cc:481] Merging Dots in computation: cluster_473__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249559.867340 3091980 dot_merger.cc:481] Merging Dots in computation: cluster_488__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249561.364569 3091983 dot_merger.cc:481] Merging Dots in computation: cluster_488__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249564.170658 3091986 dot_merger.cc:481] Merging Dots in computation: cluster_507__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249565.589318 3091980 dot_merger.cc:481] Merging Dots in computation: cluster_507__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249567.709308 3091988 dot_merger.cc:481] Merging Dots in computation: cluster_522__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249569.091323 3091983 dot_merger.cc:481] Merging Dots in computation: cluster_522__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249571.753616 3091979 dot_merger.cc:481] Merging Dots in computation: cluster_537__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249573.433297 3091984 dot_merger.cc:481] Merging Dots in computation: cluster_537__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6

[009/050] combo_009 | mean_val_rmse=0.02675288 | folds=10

I0000 00:00:1780249575.282783 3091983 dot_merger.cc:481] Merging Dots in computation: cluster_552__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249579.310965 3091979 dot_merger.cc:481] Merging Dots in computation: cluster_569__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249586.872447 3091980 dot_merger.cc:481] Merging Dots in computation: cluster_584__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249590.090749 3091988 dot_merger.cc:481] Merging Dots in computation: cluster_601__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249594.516593 3091983 dot_merger.cc:481] Merging Dots in computation: cluster_616__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249598.764812 3091983 dot_merger.cc:481] Merging Dots in computation: cluster_631__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249602.251939 3091980 dot_merger.cc:481] Merging Dots in computation: cluster_648__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6

[010/050] combo_010 | mean_val_rmse=0.03281460 | folds=10

I0000 00:00:1780249607.430231 3091988 dot_merger.cc:481] Merging Dots in computation: cluster_664__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6
I0000 00:00:1780249609.443319 3091988 dot_merger.cc:481] Merging Dots in computation: cluster_664__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6
I0000 00:00:1780249612.321428 3091986 dot_merger.cc:481] Merging Dots in computation: cluster_679__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6
I0000 00:00:1780249614.057456 3091978 dot_merger.cc:481] Merging Dots in computation: cluster_679__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6
I0000 00:00:1780249620.725661 3091988 dot_merger.cc:481] Merging Dots in computation: cluster_696__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6
I0000 00:00:1780249622.570733 3091974 dot_merger.cc:481] Merging Dots in computation: cluster_696__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6
I0000 00:00:1780249625.597386 3091974 dot_merger.cc:481] Merging Dots in computation: cluster_711__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6
I0000 00:00:1780249627.230284 3091982 dot_merger.cc:481] Merging Dots in computation: cluster_711__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6
I0000 00:00:1780249629.327538 3091988 dot_merger.cc:481] Merging Dots in computation: cluster_726__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6
I0000 00:00:1780249630.892759 3091983 dot_merger.cc:481] Merging Dots in computation: cluster_726__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6
I0000 00:00:1780249634.815493 3091980 dot_merger.cc:481] Merging Dots in computation: cluster_747__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6
I0000 00:00:1780249636.481975 3091982 dot_merger.cc:481] Merging Dots in computation: cluster_747__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6

[011/050] combo_011 | mean_val_rmse=0.03070678 | folds=10

I0000 00:00:1780249640.574463 3091980 dot_merger.cc:481] Merging Dots in computation: cluster_765__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_0__XlaNumResourceArgs_8_.5
I0000 00:00:1780249645.380031 3091980 dot_merger.cc:481] Merging Dots in computation: cluster_779__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_0__XlaNumResourceArgs_8_.5
I0000 00:00:1780249647.962964 3091974 dot_merger.cc:481] Merging Dots in computation: cluster_793__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_0__XlaNumResourceArgs_8_.5
I0000 00:00:1780249655.766876 3091980 dot_merger.cc:481] Merging Dots in computation: cluster_807__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_0__XlaNumResourceArgs_8_.5
I0000 00:00:1780249658.982022 3091985 dot_merger.cc:481] Merging Dots in computation: cluster_823__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_0__XlaNumResourceArgs_8_.5

[012/050] combo_012 | mean_val_rmse=0.02550606 | folds=10

I0000 00:00:1780249663.411983 3091986 dot_merger.cc:481] Merging Dots in computation: cluster_840__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_0__XlaNumResourceArgs_7_.5
I0000 00:00:1780249667.431659 3091976 dot_merger.cc:481] Merging Dots in computation: cluster_858__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_0__XlaNumResourceArgs_7_.5
I0000 00:00:1780249669.973548 3091973 dot_merger.cc:481] Merging Dots in computation: cluster_872__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_0__XlaNumResourceArgs_7_.5
I0000 00:00:1780249674.696614 3091988 dot_merger.cc:481] Merging Dots in computation: cluster_894__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_0__XlaNumResourceArgs_7_.5

[013/050] combo_013 | mean_val_rmse=0.02723017 | folds=10

I0000 00:00:1780249677.298784 3091982 dot_merger.cc:481] Merging Dots in computation: cluster_910__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6
I0000 00:00:1780249679.009700 3091978 dot_merger.cc:481] Merging Dots in computation: cluster_910__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6
I0000 00:00:1780249682.553757 3091983 dot_merger.cc:481] Merging Dots in computation: cluster_931__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6
I0000 00:00:1780249684.354326 3091982 dot_merger.cc:481] Merging Dots in computation: cluster_931__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6

[014/050] combo_014 | mean_val_rmse=0.02870146 | folds=10

I0000 00:00:1780249693.158957 3091988 dot_merger.cc:481] Merging Dots in computation: cluster_959__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249694.977452 3091981 dot_merger.cc:481] Merging Dots in computation: cluster_959__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249700.548022 3091973 dot_merger.cc:481] Merging Dots in computation: cluster_984__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249702.088491 3091985 dot_merger.cc:481] Merging Dots in computation: cluster_984__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249703.876083 3091986 dot_merger.cc:481] Merging Dots in computation: cluster_999__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249705.361870 3091983 dot_merger.cc:481] Merging Dots in computation: cluster_999__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6

[015/050] combo_015 | mean_val_rmse=0.03014439 | folds=10

I0000 00:00:1780249707.545191 3091978 dot_merger.cc:481] Merging Dots in computation: cluster_1014__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249708.945804 3091982 dot_merger.cc:481] Merging Dots in computation: cluster_1014__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249712.175076 3091988 dot_merger.cc:481] Merging Dots in computation: cluster_1031__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249713.641245 3091980 dot_merger.cc:481] Merging Dots in computation: cluster_1031__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249716.137210 3091985 dot_merger.cc:481] Merging Dots in computation: cluster_1048__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249717.680153 3091988 dot_merger.cc:481] Merging Dots in computation: cluster_1048__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249721.382169 3091980 dot_merger.cc:481] Merging Dots in computation: cluster_1067__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249722.993894 3091983 dot_merger.cc:481] Merging Dots in computation: cluster_1067__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249728.555852 3091978 dot_merger.cc:481] Merging Dots in computation: cluster_1082__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249730.047514 3091978 dot_merger.cc:481] Merging Dots in computation: cluster_1082__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249731.824640 3091978 dot_merger.cc:481] Merging Dots in computation: cluster_1097__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249733.368457 3091987 dot_merger.cc:481] Merging Dots in computation: cluster_1097__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6

[016/050] combo_016 | mean_val_rmse=0.02715895 | folds=10

I0000 00:00:1780249735.481631 3091987 dot_merger.cc:481] Merging Dots in computation: cluster_1114__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_0__XlaNumResourceArgs_8_.5
I0000 00:00:1780249738.354830 3091974 dot_merger.cc:481] Merging Dots in computation: cluster_1128__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_0__XlaNumResourceArgs_8_.5

[017/050] combo_017 | mean_val_rmse=0.03205960 | folds=10

I0000 00:00:1780249744.648959 3091987 dot_merger.cc:481] Merging Dots in computation: cluster_1156__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249748.224237 3091979 dot_merger.cc:481] Merging Dots in computation: cluster_1173__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249752.039705 3091978 dot_merger.cc:481] Merging Dots in computation: cluster_1188__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249755.778595 3091981 dot_merger.cc:481] Merging Dots in computation: cluster_1203__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249762.686985 3091984 dot_merger.cc:481] Merging Dots in computation: cluster_1218__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249766.040712 3091974 dot_merger.cc:481] Merging Dots in computation: cluster_1235__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249768.653534 3091976 dot_merger.cc:481] Merging Dots in computation: cluster_1250__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249771.412936 3091975 dot_merger.cc:481] Merging Dots in computation: cluster_1265__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6

[018/050] combo_018 | mean_val_rmse=0.04199594 | folds=10

I0000 00:00:1780249775.474912 3091982 dot_merger.cc:481] Merging Dots in computation: cluster_1286__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249777.398930 3091985 dot_merger.cc:481] Merging Dots in computation: cluster_1286__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249782.921683 3091972 dot_merger.cc:481] Merging Dots in computation: cluster_1307__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249784.477101 3091984 dot_merger.cc:481] Merging Dots in computation: cluster_1307__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249786.646800 3091985 dot_merger.cc:481] Merging Dots in computation: cluster_1324__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249788.289141 3091982 dot_merger.cc:481] Merging Dots in computation: cluster_1324__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6

[019/050] combo_019 | mean_val_rmse=0.02962396 | folds=10

I0000 00:00:1780249792.121427 3091986 dot_merger.cc:481] Merging Dots in computation: cluster_1344__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6
I0000 00:00:1780249793.659962 3091978 dot_merger.cc:481] Merging Dots in computation: cluster_1344__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6
I0000 00:00:1780249799.399957 3091977 dot_merger.cc:481] Merging Dots in computation: cluster_1359__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6
I0000 00:00:1780249801.028354 3091985 dot_merger.cc:481] Merging Dots in computation: cluster_1359__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6
I0000 00:00:1780249802.947626 3091973 dot_merger.cc:481] Merging Dots in computation: cluster_1374__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6
I0000 00:00:1780249804.509642 3091973 dot_merger.cc:481] Merging Dots in computation: cluster_1374__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6

[020/050] combo_020 | mean_val_rmse=0.02414800 | folds=10

I0000 00:00:1780249809.791117 3091968 dot_merger.cc:481] Merging Dots in computation: cluster_1399__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6
I0000 00:00:1780249811.600257 3091985 dot_merger.cc:481] Merging Dots in computation: cluster_1399__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6
I0000 00:00:1780249815.852770 3091968 dot_merger.cc:481] Merging Dots in computation: cluster_1420__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6
I0000 00:00:1780249818.718491 3091972 dot_merger.cc:481] Merging Dots in computation: cluster_1420__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6
I0000 00:00:1780249822.352053 3091980 dot_merger.cc:481] Merging Dots in computation: cluster_1437__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6
I0000 00:00:1780249824.611630 3091975 dot_merger.cc:481] Merging Dots in computation: cluster_1437__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6

[021/050] combo_021 | mean_val_rmse=0.02893388 | folds=10

I0000 00:00:1780249828.758622 3091974 dot_merger.cc:481] Merging Dots in computation: cluster_1457__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249834.590926 3091983 dot_merger.cc:481] Merging Dots in computation: cluster_1457__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249836.970828 3091975 dot_merger.cc:481] Merging Dots in computation: cluster_1474__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249838.878276 3091985 dot_merger.cc:481] Merging Dots in computation: cluster_1474__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249840.704521 3091985 dot_merger.cc:481] Merging Dots in computation: cluster_1489__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249842.588335 3091979 dot_merger.cc:481] Merging Dots in computation: cluster_1489__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249844.607619 3091985 dot_merger.cc:481] Merging Dots in computation: cluster_1504__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249846.465454 3091980 dot_merger.cc:481] Merging Dots in computation: cluster_1504__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249849.104384 3091985 dot_merger.cc:481] Merging Dots in computation: cluster_1519__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249851.234743 3091980 dot_merger.cc:481] Merging Dots in computation: cluster_1519__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249853.510139 3091977 dot_merger.cc:481] Merging Dots in computation: cluster_1536__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249856.098792 3091974 dot_merger.cc:481] Merging Dots in computation: cluster_1551__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249857.566879 3091972 dot_merger.cc:481] Merging Dots in computation: cluster_1551__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6

[022/050] combo_022 | mean_val_rmse=0.02615836 | folds=10

I0000 00:00:1780249860.145002 3091977 dot_merger.cc:481] Merging Dots in computation: cluster_1568__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249861.829489 3091980 dot_merger.cc:481] Merging Dots in computation: cluster_1568__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249864.775102 3091983 dot_merger.cc:481] Merging Dots in computation: cluster_1585__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249871.848723 3091977 dot_merger.cc:481] Merging Dots in computation: cluster_1585__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249875.492017 3091983 dot_merger.cc:481] Merging Dots in computation: cluster_1600__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249877.460246 3091977 dot_merger.cc:481] Merging Dots in computation: cluster_1600__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249880.598197 3091977 dot_merger.cc:481] Merging Dots in computation: cluster_1615__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249882.761598 3091980 dot_merger.cc:481] Merging Dots in computation: cluster_1615__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249886.207272 3091977 dot_merger.cc:481] Merging Dots in computation: cluster_1630__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249893.086369 3091968 dot_merger.cc:481] Merging Dots in computation: cluster_1630__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249899.069896 3091973 dot_merger.cc:481] Merging Dots in computation: cluster_1645__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249910.449506 3091976 dot_merger.cc:481] Merging Dots in computation: cluster_1645__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6

[023/050] combo_023 | mean_val_rmse=0.03403965 | folds=10

I0000 00:00:1780249920.853018 3091971 dot_merger.cc:481] Merging Dots in computation: cluster_1666__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249928.339606 3091971 dot_merger.cc:481] Merging Dots in computation: cluster_1666__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249944.609665 3091971 dot_merger.cc:481] Merging Dots in computation: cluster_1681__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780249961.621291 3091967 dot_merger.cc:481] Merging Dots in computation: cluster_1681__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780250016.653644 3091960 dot_merger.cc:481] Merging Dots in computation: cluster_1698__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780250022.795062 3091965 dot_merger.cc:481] Merging Dots in computation: cluster_1698__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780250028.237850 3091967 dot_merger.cc:481] Merging Dots in computation: cluster_1713__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780250035.058040 3091966 dot_merger.cc:481] Merging Dots in computation: cluster_1713__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780250049.978911 3091960 dot_merger.cc:481] Merging Dots in computation: cluster_1732__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780250060.127005 3091960 dot_merger.cc:481] Merging Dots in computation: cluster_1732__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780250078.846350 3091966 dot_merger.cc:481] Merging Dots in computation: cluster_1749__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6
I0000 00:00:1780250112.739457 3091974 dot_merger.cc:481] Merging Dots in computation: cluster_1749__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_9_.6

[024/050] combo_024 | mean_val_rmse=0.03126344 | folds=10

I0000 00:00:1780250208.730952 3091963 dot_merger.cc:481] Merging Dots in computation: cluster_1765__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6
I0000 00:00:1780250320.555354 3091964 dot_merger.cc:481] Merging Dots in computation: cluster_1765__XlaCompiledKernel_true__XlaHasReferenceVars_false__XlaNumConstantArgs_1__XlaNumResourceArgs_10_.6

In [ ]:
def evaluate_on_folds(data: pd.DataFrame, folds: list[dict], params: dict, output_dir: Path, fold_set_name: str) -> tuple[pd.DataFrame, pd.DataFrame]:
    output_dir.mkdir(parents=True, exist_ok=True)

    all_fold_metrics: list[dict] = []
    all_preds: list[pd.DataFrame] = []

    for fold in folds:
        fold_result = train_one_fold(
            data=data,
            fold=fold,
            params=params,
            combo_dir=output_dir,
            fold_set_name=fold_set_name,
        )
        if fold_result is None:
            continue

        all_fold_metrics.append(fold_result)
        pred_df = pd.read_csv(fold_result['predictions_path'])
        pred_df['fold_id'] = fold_result['fold_id']
        all_preds.append(pred_df)

    if not all_fold_metrics:
        raise RuntimeError(f'No folds trained for {fold_set_name}')

    metrics_df = pd.DataFrame(all_fold_metrics).sort_values('fold_id').reset_index(drop=True)
    preds_df = pd.concat(all_preds, ignore_index=True)

    metrics_df.to_csv(output_dir / f'{fold_set_name}_fold_metrics.csv', index=False)
    preds_df.to_csv(output_dir / f'{fold_set_name}_predictions.csv', index=False)

    return metrics_df, preds_df


final_dir = ARTIFACTS_DIR / 'final_evaluation'
val_metrics_df, val_preds_df = evaluate_on_folds(df, val_folds, best_params, final_dir, 'validation')
test_metrics_df, test_preds_df = evaluate_on_folds(df, test_folds, best_params, final_dir, 'test')

print('Validation fold metrics (mean):')
display(val_metrics_df[['rmse', 'mae']].mean().to_frame('value'))
print('Test fold metrics (mean):')
display(test_metrics_df[['rmse', 'mae']].mean().to_frame('value'))

In [ ]:
# Quick diagnostics
plt.figure(figsize=(14, 5))
plot_df = test_preds_df.copy()
plot_df[TIMESTAMP_COL] = pd.to_datetime(plot_df[TIMESTAMP_COL], utc=True)
plot_df = plot_df.sort_values(TIMESTAMP_COL)

plt.plot(plot_df[TIMESTAMP_COL], plot_df['y_true'], label='True', alpha=0.8)
plt.plot(plot_df[TIMESTAMP_COL], plot_df['y_pred'], label='Predicted', alpha=0.8)
plt.title('Test Walk-Forward Predictions (next daily return)')
plt.xlabel('Timestamp (UTC)')
plt.ylabel('Log return')
plt.legend()
plt.tight_layout()
plt.show()

summary = {
    'val_rmse_mean': float(val_metrics_df['rmse'].mean()),
    'val_mae_mean': float(val_metrics_df['mae'].mean()),
    'test_rmse_mean': float(test_metrics_df['rmse'].mean()),
    'test_mae_mean': float(test_metrics_df['mae'].mean()),
    'best_params': best_params,
}

with (ARTIFACTS_DIR / 'summary.json').open('w', encoding='utf-8') as f:
    json.dump(summary, f, indent=2)

summary

## Notes

- The notebook saves intermediate and best artifacts into `artifacts/lstm_walk_forward/`.
- Target variable is daily return `r_t = log(P_t / P_{t-1})`, predicted one day ahead.
- `ModelCheckpoint` + `BackupAndRestore` keep progress safe if training is interrupted.
- TensorBoard starts automatically at training time on `http://127.0.0.1:6006` (if `AUTO_START_TENSORBOARD=True`) when the `tensorboard` package is installed, and logs to `artifacts/lstm_walk_forward/tensorboard/`.
- For CUDA speedups, this notebook auto-detects GPUs, enables memory growth, XLA, and mixed precision.
- If CUDA is required, set `REQUIRE_CUDA = True` in the config cell to fail fast when no GPU is available.
- To make training faster/slower, adjust `GRID_LIMIT`, `FOLD_STEP_DAYS`, and `MAX_EPOCHS`.